markdown: kramdown
url: www.parulbhargava.com
theme: jekyll-theme-merlot
title: Getting to Think
show_downloads: false
description: To inspire and accept people, enabling them to be their authentic selves